### ISSUE TITLE
Headers section should include X-Forwarded-Proto

### ISSUE THREAD

**Issue by mdobson** [apigee/microgateway-core#46]
Currently the config headers section is defined as follows:

```yaml
headers:
  x-forwarded-for: true
  x-forwarded-host: true
  x-request-id: true
  x-response-time: true
  via: true
```

It should also include the `X-Forwarded-Proto` header as well
