### ISSUE TITLE
Cannot use self-signed certificates to connect to backend server

### ISSUE THREAD

**Issue by dod38fr** [apigee/microgateway-core#56]
Hello

By default, EMG checks server certificates' trust using SSL to connect to target backend server. This is [https](https://nodejs.org/api/https.html) default setting. 

This setting is not practical when testing against a server which only has self-signed certificates. Unfortunately, there's no possibility to let EMG set `rejectUnauthorized` https option to allow self-signed certificate.

Could you add an option to EMG to enable using self-signed certificates ?

All the best

NB: The workaround to to add `rejectUnauthorized:false` to [targetRequestOptions in plugins-middleware.js](https://github.com/apigee/microgateway-core/blob/master/lib/plugins-middleware.js#L164)

**Comment by mdobson** [comment]
Hi @dod38fr 

Actually Edgemicro will allow you to configure ssl to target endpoints on by host basis. Due to the wide range of use cases for edgemicro this seems like the best approach. It would actually be in there that you set `rejectUnauthorized: false`.

To do this you need to actually add another section in your configuration file. It'd look something like this.
```
targets:
  - host: 'subdomain.example.com'
    ssl:
      client:
        key: "/var/tmp/certs/ca.key"
        cert: "/var/tmp/certs/ca.crt"
        rejectUnauthorized: false
```
